const CATALOG = [
    {
        id: 'el1',
        name: 'Видеокарта MSI GeForce RTX 4070 VENTUS 3X E OC [GeForce RTX 4070 VENTUS 3X E 12G OC]',
        img: './img/catalog/Видеокарта MSI GeForce RTX 4070 VENTUS 3X E OC.jpg',
        price: 66999,
        rating: 5,
    },
    {
        id: 'el2',
        name: 'Видеокарта MSI GeForce RTX 4060 VENTUS 2X BLACK OC [GeForce RTX 4060 VENTUS 2X]',
        img: './img/catalog/Видеокарта MSI GeForce RTX 4060 VENTUS 2X BLACK OC.jpg',
        price: 38799,
        rating: 5,
    },
    {
        id: 'el3',
        name: 'Видеокарта KFA2 GeForce RTX 4060 CORE Black [46NSL8MD9NXK]',
        img: './img/catalog/Видеокарта KFA2 GeForce RTX 4060 CORE Black.jpg',
        price: 32999,
        rating: 5,
    },
    {
        id: 'el4',
        name: 'Видеокарта Sapphire AMD Radeon RX 6600 PULSE [11310-01-20G]',
        img: './img/catalog/Видеокарта Sapphire AMD Radeon RX 6600 PULSE.jpg',
        price: 24999,
        rating: 5,
    },
    {
        id: 'el5',
        name: 'Видеокарта Palit GeForce RTX 4070 Ti JetStream [NED407T019K9-1043J]',
        img: './img/catalog/Видеокарта Palit GeForce RTX 4070 Ti JetStream.jpg',
        price: 82999,
        rating: 5,
    },
    {
        id: 'el6',
        name: 'Видеокарта KFA2 GeForce RTX 3050 X White [35NSL8MD5WEK]',
        img: './img/catalog/Видеокарта KFA2 GeForce RTX 3050 X White.jpg',
        price: 25999,
        rating: 5,
    },
    {
        id: 'el7',
        name: 'Видеокарта Sapphire AMD Radeon RX 7800 XT NITRO+ [11330-01-20G]',
        img: './img/catalog/Видеокарта Sapphire AMD Radeon RX 7800 XT NITRO+.jpg',
        price: 67999,
        rating: 5,
    },
    {
        id: 'el8',
        name: 'Видеокарта MSI GeForce RTX 4080 SUPER EXPERT [912-V511-238]',
        img: './img/catalog/Видеокарта MSI GeForce RTX 4080 SUPER EXPERT.jpg',
        price: 149999,
        rating: 5,
    },
    {
        id: 'el9',
        name: 'Видеокарта Sapphire AMD Radeon RX 7900 XT PULSE OC [11323-02-20G]',
        img: './img/catalog/Видеокарта Sapphire AMD Radeon RX 7900 XT PULSE OC.jpg',
        price: 90799,
        rating: 5,
    },
    {
        id: 'el10',
        name: 'Видеокарта MSI GeForce GT 710 Silent LP [GT 710 2GD3H LP]',
        img: './img/catalog/Видеокарта MSI GeForce GT 710 Silent LP.jpg',
        price: 4599,
        rating: 5,
    },
];